### ISSUE TITLE
你好，请问一下目标检测子任务的list_test.txt里面文件是什么呢？

### ISSUE THREAD

**Issue by gittigxuy** [xxbbml/VideoNet_Baseline#3]
是不是所有预测图片的全路径呢？
我已经生成了这个txt文件，但是在detect.py文件中的第72行报错了，具体是在utils/dataset.py的第136行读不到targets变量，请问一下应该如何解决呢？

**Comment by xxbbml** [comment]
更新了一下convert_yolo_format.py，可以检查一下是否使用convert_yolo_format.py生成了测试图片的list和label，list是所有图片的地址，label是每张图有一个'0 0 0 0 0'的txt文件。
