### ISSUE TITLE
有关目标检测子任务的测评问题

### ISSUE THREAD

**Issue by gittigxuy** [xxbbml/VideoNet_Baseline#5]
你好，我看到了你的baseline的detection.py里面的代码，生成json结果文件的策略是生成当前图片中概率最大的目标，请问一下
1）如果类别预测错误，但是框的大概位置正确，会影响最终的测评结果吗？毕竟你们的测评是IOU>0.5
2)如果当前图概率最大的类别预测错误，但是概率第二大的类别预测正确，可否在生成最终的json文件中一张图片生成多个目标框？

**Comment by xxbbml** [comment]
1. 类别与IOU需与goundtruth中任意结果一致才会判定正确，类别预测错误将会判定错误。
2. 即使结果生成多个目标框，在分数计算时评价程序只会取第一个预测结果进行计算。

**Comment by gittigxuy** [comment]
那就是gt里面有多个结果，但是我提交的结果只能是一张图中所有预测目标当中的任意一个，并且我的这个目标的类别要正确，并且和GT的iou还要大于0.5，是这么理解是吧？

**Comment by xxbbml** [comment]
> 那就是gt里面有多个结果，但是我提交的结果只能是一张图中所有预测目标当中的任意一个，并且我的这个目标的类别要正确，并且和GT的iou还要大于0.5，是这么理解是吧？

是的。

**Comment by gittigxuy** [comment]
好的，麻烦提供一个线下测评的脚本文件，感谢回复
