### ISSUE TITLE
使用generate_submission.py文件生成json结果文件之后，不能提交

### ISSUE THREAD

**Issue by gittigxuy** [xxbbml/VideoNet_Baseline#6]
显示“文件格式必须为json”

**Comment by xxbbml** [comment]
您好，我们检查了generate_submission.py以及网盘中的baseline.json，并测试提交成功，请再检查下自己的设置是否有其他问题，谢谢！

![WechatIMG174](https://user-images.githubusercontent.com/9065096/61264413-18e89a80-a7bf-11e9-98c1-48ba70e234f5.jpeg)
![WechatIMG175](https://user-images.githubusercontent.com/9065096/61264415-1c7c2180-a7bf-11e9-925d-d7144ac9001a.jpeg)

**Comment by Caoliangjie** [comment]
[您好，我们从您的网盘链接里下了baseline提交也是楼主这样的错误，请问是怎么回事？
![image](https://user-images.githubusercontent.com/38064559/61298426-c33cde00-a810-11e9-8daa-a382bff2c0e2.png)

**Comment by gittigxuy** [comment]
@Caoliangjie ,换成火狐浏览器就可以了

**Comment by Caoliangjie** [comment]
> @Caoliangjie ,换成火狐浏览器就可以了

谢谢，最后发现是科学上网的问题TAT
