### ISSUE TITLE
请问您的tsn baseline是训练了多少epoch后的结果

### ISSUE THREAD

**Issue by JacobKong** [xxbbml/VideoNet_Baseline#8]
请问您的tsn baseline是训练了多少epoch后的结果在验证集上才到了77？

期待您的回复

**Comment by xxbbml** [comment]
TSN 是训练了65个epoch.

**Comment by JacobKong** [comment]
> TSN 是训练了65个epoch.

那您是使用的下面的官方ReadMe中的setting进行训练的吗，因为我通过下面的setting复现，只是把batchsize设为64，结果只能跑出70%的性能
--arch BNInception --num_segments 3 --gd 20 --lr 0.001 --lr_steps 30 60 --epochs 80 -b 128 -j 8 --dropout 0.8 --snapshot_pref VideoNet_bninception_  --gpus 0 1 2 3

**Comment by xxbbml** [comment]
我们是使用ReadMe中的设定进行训练的。在测试时，使用10 crops进行预测会对结果有提升。
