### ISSUE TITLE
scene/class_to_idx.json的作用是什么？

### ISSUE THREAD

**Issue by CuiZhiying** [xxbbml/VideoNet_Baseline#9]
你好，想问一下在scene任务中，提供的baseline model在数据训练之前对场景分类的标签进行了重新映射，不知道这样子的映射的作用是什么？我在官网和github中均没有找到说明，特来请教。期盼您的回复：）

**Comment by xxbbml** [comment]
这个class_to_idx.json是由于之前在训练时标签映射的一个问题，导致baseline模型学习了映射后的标签。我们后来针对代码进行了修改，如自行训练时可以直接使用场景分类标签作为class_to_idx.json，只要保证模型训练和预测的标签一致即可。

**Comment by CuiZhiying** [comment]
也就是，我自己用自己的代码训练的话，就直接使用这个文档extract_keyframes.py提取的关键帧提取的标签进行训练就好了，不用进行重新映射 ？若果是使用这里的placeCNN进行训练的话，就使用这个新的映射？能够具体说明一下这个标签映射的问题出现在哪里嘛？

**Comment by xxbbml** [comment]
PlaceCNN之前训练时是把不同类别的帧放在不同的文件夹里，因此对于文件夹有一个类别的重新映射。我们之后把代码修改成只要输入图片列表即可，但模型保留了之前映射的类别。
如果想用baseline的模型进行预测，需要使用class_to_idx.json的映射。
如果用baseline的代码重新训练，可以在/scene/utils/VideoNet.py里修改39行 class_to_idx = json.load(open('class_to_idx.json','r')) 为label的顺序。
如果用其他代码，可以自由选择如何训练。

**Comment by CuiZhiying** [comment]
了解，非常感谢！
